# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

variables:
# common task variables
- name: 'BuildConfiguration'
  value: 'Release'
- name: 'SolutionFile'
  value: 'AspNetCoreAngularSample.sln'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1.100'
  inputs:
    packageType: 'sdk'
    version: '3.1.100'

- task: Npm@1
  displayName: 'Install the NPM packages'
  inputs:
    command: 'install'
    workingDir: 'src/WebApp/ClientApp'

- task: Npm@1
  displayName: 'Run Angular lint'
  inputs:
    command: 'custom'
    customCommand: 'run ng lint'
    workingDir: 'src/WebApp/ClientApp'

- task: DotNetCoreCLI@2
  displayName: 'Build .NET solution'
  inputs:
    command: 'build'
    projects: $(SolutionFile)
    arguments: '-c $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run Test'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)/Deployment'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/Deployment'

- task: DotNetCoreCLI@2
  displayName: 'Publish the web app'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Save the artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
  condition: succeededOrFailed()


